{{- if .Values.experimental.kubernetesServiceAPI.enabled }}
---
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: traefik
spec:
  controller: traefik.io/gateway-controller
--- 
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata: 
  name: traefik-gateway
  namespace: default
spec: 
  gatewayClassName: traefik
  listeners: 
    - 
      port: {{ .Values.ports.web.port }}
      protocol: HTTP
      routes: 
        kind: HTTPRoute
        namespaces: 
          from: Same
        selector: 
          matchLabels: 
            app: {{ .Values.experimental.kubernetesServiceAPI.appLabelSelector }}

    {{- range $index, $cert:= .Values.experimental.kubernetesServiceAPI.certificates }}
    - 
      port: {{ .Values.ports.websecure.port }}
      protocol: HTTPS
      routes: 
        kind: HTTPRoute
        selector: 
          matchLabels: 
            app: {{ .Values.experimental.kubernetesServiceAPI.appLabelSelector }}
      tls: 
        {{- with .Values.experimental.kubernetesServiceAPI.certificates }}
        certificateRef: :
        {{- toYaml . | nindent 6 }}
        {{- end }}
    {{- end }}
{{- end }}