{{- if .Values.experimental.kubernetesServiceAPI.enabled }}
--- 
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata: 
  name: traefik-gateway
  namespace: default
spec: 
  gatewayClassName: traefik
  listeners: 
    - 
      port: {{ .Values.ports.web.port }}
      protocol: HTTP
      routes: 
        kind: HTTPRoute
        selector: 
          matchLabels: 
            app: {{ .Values.experimental.kubernetesServiceAPI.appLabelSelector }}
    {{- range $index, $cert:= .Values.experimental.kubernetesServiceAPI.certificates }}
    - 
      port: {{ $.Values.ports.websecure.port }}
      protocol: HTTPS
      tls:
        certificateRef:
          name: {{ $cert.name }}
          group: {{ $cert.group }}
          kind: {{ $cert.kind }}
      routes: 
        kind: HTTPRoute
        selector: 
          matchLabels: 
            app: {{ $.Values.experimental.kubernetesServiceAPI.appLabelSelector }}
    {{- end }}
{{- end }}